### PR TITLE
An article about building and testing Bioc packages for Linux ARM64

### PR DESCRIPTION
**Pull request by martin-g**
The article is an adapted version of
https://martin-grigorov.medium.com/emulated-building-and-testing-of-bioconductor-projects-for-linux-arm64-501c1f854dc1

It uses
https://bioconductor.org/images/logo/svg/bioconductor_logo_cmyk.svg with a small modification (added text "on Linux ARM64") done by me with Krita image editor.

### CODE REVIEW

**Review by LiNk-NY — APPROVED** [review]
Looks good to me! Thanks

**Comment by hpages** [comment]
Thanks @martin-g! So who is in charge of approving/merging/publishing?

**Comment by LiNk-NY** [comment]
I would guess either @mblue9 or @kozo2 ?

**Comment by mblue9** [comment]
Happy to merge, I've just 2 minor questions first.

- Could a sentence be added at the beginning on why people might be interested to do this (e.g. to reduce expenses, as in https://github.com/Bioconductor/BBS/pull/255#issuecomment-1554418244), to help people not working in this area understand the context better?

- There aren't many biocblog tags so far and none that really fit this. Bioc seems a bit too general, what about adding a new tag like `tech notes` (like https://ropensci.org/tags/)?

**Comment by martin-g** [comment]
Thanks for the comments!
I've updated the tag and added a short paragraph why one might use ARM64.

**Review by mblue9 — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
