### PR TITLE
scholar_blogpost

### PR DESCRIPTION
**Pull request by Scholarpat**
In this post, I have shared my journey, detailing my experience working on the Microbiome Study Curation project and Bioconductor in general.

### CODE REVIEW

**Comment by jwokaty** [comment]
@Scholarpat This is a great , thoughtfully written and well organized blog post.

I have just a few requests for changes before it's published:
- [ ] The images didn't load for me. This might be because their extensions are capitalized--e.g., `outreachy.PNG`. I recommend renaming the files with lowercase extensions. Make sure the images display when you build the blog.
- [ ] Similarly, I recommend making `Index.qmd` lowercase to `index.qmd`.
- [ ] Let's use "open source" and also "open science" without the dash/hypen "-".
- [ ] On line 42, did you mean to include a link to your blog somewhere in the text: "I wrote more about My Journey with Outreachy and the Bioconductor Community in this blog post."?

I was thinking that this type of blog post is a "series" in the same way that we write about the Bioconductor conference (we write "BioC2024"), so it might make sense for us to say "Outreachy May 2024" in the title to make it more specific. What do you think?

**Comment by Scholarpat** [comment]
Hi Jennifer,

Thank you so much for your kind words and feedback on my blog post! I’m
glad you found it thoughtfully written and well-organized.

I’ve made the adjustments you suggested:

   - The image files have been renamed with lowercase extensions, and they
   display correctly when the blog is built.
   - I’ve renamed Index.qmd to index.qmd.
   - I’ve updated the text to use "open source" and "open science" without
   the hyphen.
   - I’ve also added the link to my blog post on line 42.


I agree that "Outreachy May 2024" makes the title more specific and aligns
well with our other series titles, so I’ve made that change too.

Thanks again for your guidance, and please let me know if there’s anything
else you’d like me to adjust!

Best regards,
Scholastica

**Comment by jwokaty** [comment]
Hi @Scholarpat, thanks for addressing these issues. I noticed there's 1 more instance of 'Open-Source'. Did you forget to add your commit changing 'Index.qmd' to 'index.qmd'? It appears unchanged.

I think after those 2 items, I think we can ask if it's okay to publish.

**Comment by Scholarpat** [comment]
Hi @jwokaty,

Thank you for pointing that out. I’ve corrected the remaining instance of 'Open-Source' as you mentioned.

Regarding the 'Index.qmd' issue, I’ve made several attempts to change it to 'index.qmd,' but it doesn’t seem to reflect the changes. If you’re available, could you please guide me through resolving this issue? Thank you.

image

**Comment by jwokaty** [comment]
@Scholarpat Thanks for your blog post!

@mblue9 Can we merge this post?

**Comment by mblue9** [comment]
Yes, the post looks great! I will merge it. Thanks, @Scholarpat , for your work on this. I just added an image to ensure it appears correctly on the listing page. Nice job!

**Comment by mblue9** [comment]
@Scholarpat one quick tip for future contributions: it's a good idea to create a new branch for each post or feature you work on, instead of working directly on your `main` branch. This keeps things organised and makes it easier to manage your work. If you ever need help with branching or anything else, feel free to ask!

**Comment by Scholarpat** [comment]
Thank you for the tip @mblue9! I appreciate the advice on creating a new branch for each post or feature—I'll make sure to do that going forward. If I run into any challenges with branching or anything else, I'll definitely reach out. Thanks again!

**Pull request merged**
