### PR TITLE
Adding a new blog post

### PR DESCRIPTION
**Pull request by JauntyJJS**
Hi,

I have made a new post regarding some web links to different Awesome Lists that may be useful to those just starting up in bioinformatics and those experienced in the field.

### CODE REVIEW

**Comment by kozo2** [comment]
@JauntyJJS Thanks for your PR!
I think your awesome-list link idea is great.
But it would be nice if the link to the Bioconductor package was clearer.
I would like to co-update your post.

**Comment by kozo2** [comment]
I will extract the Bioconductor packages in awesome-lipidomics.

**Comment by kozo2** [comment]
https://github.com/lifs-tools/awesome-lipidomics
contains following Bioconductor packages
## [Programs & Libraries for Lipid Identification](https://github.com/lifs-tools/awesome-lipidomics#programs--libraries-for-lipid-identification)
- [LOBSTAHS](http://bioconductor.org/packages/release/bioc/html/LOBSTAHS.html)
- [xcms](http://bioconductor.org/packages/release/bioc/html/xcms.html)
## [Post Processing, Visualization and Statistical Analysis](https://github.com/lifs-tools/awesome-lipidomics#post-processing-visualization-and-statistical-analysis)
- [rgoslin](http://bioconductor.org/packages/release/bioc/html/rgoslin.html)
- [lipidr](http://bioconductor.org/packages/release/bioc/html/lipidr.html)
## [Databases, Repositories and other Resources](https://github.com/lifs-tools/awesome-lipidomics#databases-repositories-and-other-resources)
- [HMDB(biodbHmdb)](http://bioconductor.org/packages/release/bioc/manuals/biodbHmdb/man/biodbHmdb.pdf)
- [Lipid Maps(biodbLipidMaps)](http://bioconductor.org/packages/release/bioc/manuals/biodbLipidmaps/man/biodbLipidmaps.pdf)
- [MassBank(RMassBank)](http://bioconductor.org/packages/release/bioc/html/RMassBank.html)
- [MetaboLights(mtbls2)](https://bioconductor.org/packages/release/data/experiment/html/mtbls2.html)

**Comment by mblue9** [comment]
These are the ones with Bioconductor urls in awesome-single-cell

- [cellTree](https://www.bioconductor.org/packages/release/bioc/html/cellTree.html)
- [countsimQC](https://www.bioconductor.org/packages/release/bioc/html/countsimQC.html)
- [dittoSeq](https://bioconductor.org/packages/release/bioc/html/dittoSeq.html)
- [scran](http://bioconductor.org/packages/release/bioc/html/scran.html)
- [sincell](http://bioconductor.org/packages/release/bioc/html/sincell.html)
- [scater](https://bioconductor.org/packages/release/bioc/html/scater.html)
- [destiny](http://bioconductor.org/packages/release/bioc/html/destiny.html)
- [scmap](http://bioconductor.org/packages/release/bioc/html/scmap.html)
- [splatter](http://bioconductor.org/packages/release/bioc/html/splatter.html) 
- [SingleR](https://bioconductor.org/packages/release/bioc/html/SingleR.html)
- [AneuFinder](https://bioconductor.org/packages/release/bioc/html/AneuFinder.html)
- [ChromVAR](https://bioconductor.org/packages/release/bioc/html/chromVAR.html)

**Comment by kozo2** [comment]
@JauntyJJS Now I just found out that you are more pro at Lipidomics than me, sorry...

**Comment by JauntyJJS** [comment]
Hi @kozo2 and @mblue9 , I have added a preview image and created the list bioconductor packages as collapsed callout tips.

I have decided to collapse the callout tip so that the blog post will not be so long.

image

**Comment by kozo2** [comment]
@JauntyJJS Thank you for your contribution!
I merged your pull request!
I will send you a comment again when the blog is deployed and published!

**Pull request merged**
